# Generated by Django 5.0.4 on 2024-06-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtcoderContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=50, verbose_name='contest_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_time', models.CharField(max_length=50, verbose_name='start_time')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='contest_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_time', models.CharField(max_length=50, verbose_name='start_time')),
                ('length', models.CharField(max_length=50, verbose_name='length')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='code_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
        migrations.CreateModel(
            name='ContestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='contest_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('problem_id', models.IntegerField(verbose_name='problem_id')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='pNumber')),
                ('title', models.CharField(max_length=50, verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('link', models.CharField(max_length=50, verbose_name='link')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
        ),
    ]
