# Generated by Django 5.0.4 on 2024-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('problem_id', models.IntegerField(verbose_name='problem_id')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='user')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
    ]
