# Generated by Django 5.0.4 on 2024-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_problemset_remove_userinfo_user_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='contest_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_time', models.CharField(max_length=50, verbose_name='start_time')),
                ('length', models.CharField(max_length=50, verbose_name='length')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
