# Generated by Django 5.0.4 on 2024-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_codeforcescontestinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtcoderContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=50, verbose_name='contest_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_time', models.CharField(max_length=50, verbose_name='start_time')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
    ]
