# Generated by Django 5.0.4 on 2024-05-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_atcodercontestinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteproblem',
            old_name='username',
            new_name='user',
        ),
    ]
